site_url: https://divs17.github.io/deepfake-sample-outputs/
use_directory_urls: false
site_name: DeepFake Sample Outputs
theme:
  name: material
nav:
  - Home: index.md
  - Image Samples: image.md
  - Video Samples: video.md
  - Audio Samples: audio.md

