site_name: DeepFake Sample Outputs
theme:
  name: material
nav:
  - Home: index.md
  - Image Samples: image.md
  - Video Samples: video.md
  - Audio Samples: audio.md

extra_javascript: []
extra_css: []

extra:
  include_media:
    - video/output-4.mp4
    - video/output-5.mp4
    - video/qwerty.mp4
    - video/trump-dicaprio.mp4

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.snippets
  - attr_list
  - md_in_html
